name: Deploy to Test Server

on:
  push:
    branches:
      - main  # このブランチにプッシュされたときに動作する

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH to Test Server and Pull Changes
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.SECRET_HOST }}
        username: ${{ secrets.SECRET_USER }}
        key: ${{ secrets.SECRET_SSHKEY }}
        passphrase: ${{ secrets.SECRET_PASSPHRASE }}
        script: |
          cd /home/d-nak/Desktop/08-Actions
          git pull origin main
          npm install
          pm2 stop server
          pm2 start server
