name: Deploy to Test Server

on:
  push:
    branches:
      - main  # このブランチにプッシュされたときに動作する

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH to Test Server and Pull Changes
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.TEST_SERVER_HOST }}
        username: ${{ secrets.TEST_SERVER_USER }}
        key: ${{ secrets.TEST_SERVER_SSH_KEY }}
        script: |
          cd /path/to/project/on/test-server
          git pull origin main
          npm install
          pm2 stop server
          pm2 start server
