name: Deploy to Self-hosted Runner

on:
  push:
    branches:
      - main # このブランチにプッシュされたときに動作する

jobs:
  deploy:
    # Self-hosted runnerを使用
    runs-on: self-hosted

    steps:
      - name: Stop running app
        run: |
          pm2 stop dev || true

      - name: Pull latest changes
        run: |
          cd /home/d-nak/miatiadev/08-Actions
          git pull origin main

      - name: Install Dependencies
        run: |
          cd /home/d-nak/miatiadev/08-Actions
          npm install

      - name: Restart app
        run: |
          cd /home/d-nak/miatiadev/08-Actions
          pm2 start npm --name dev -- run dev
